- name: Enable password autentication 
  replace: 
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
    backup: yes

- name: Append RSA authentication 
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "RSAAuthentication yes"

- name: Append master to etc/hosts
  lineinfile:
    path: /etc/hosts
    create: yes
    state: present
    line: "{{ item }}\tmaster"
  with_items: "{{ groups['Server'] }}"

- name: Append slaves to etc/hosts
  lineinfile:
    path: /etc/hosts
    create: yes
    state: present
    line: "{{ item }}\tslave{{my_idx|int+1}}"
  with_items: "{{ groups['Client'] }}"
  loop_control:
    index_var: my_idx

- name: Append ssh public key
  lineinfile:
    path: "/home/{{ user }}/.ssh/authorized_keys"
    create: yes
    state: present
    line: "{{ hostvars['172.17.177.21']['public_key']['stdout'] }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
